import Footer from '@/Components/Footer';
import Header from '@/Components/Header';
import Trial from '@/Components/Trial';

import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Your SaaS Company</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div>
                <h1>TEST</h1>
                <Header />
                <Trial />
                <Footer />
            </div>
        </>
    );
}
